<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aidOaRtHackatonArTNg" nsURI="http:///aidOaRtHackatonArTNg.ecore"
    nsPrefix="aidOaRtHackatonArTNg">
  <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
    <details key="originalName" value="AIDOaRt_Hackaton_ART-NG"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="MandatoryDesignUnit" eSuperTypes="#//DesignUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="DesignUnit" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DesignUnitWithVariants" eSuperTypes="#//DesignUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="OptionalDesignUnit" eSuperTypes="#//DesignUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="Mechanical">
    <eStructuralFeatures xsi:type="ecore:EReference" name="m1" ordered="false" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wearplate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="m1" ordered="false" lowerBound="1"
        eType="#//Mechanical" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialNumber" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fgiCaf" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Spillguard">
    <eStructuralFeatures xsi:type="ecore:EReference" name="m1" ordered="false" lowerBound="1"
        eType="#//Mechanical" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialNumber" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fgiCaf" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tailgate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="m1" ordered="false" lowerBound="1"
        eType="#//Mechanical" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="m2" ordered="false" lowerBound="1"
        eType="#//Mechanical" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialNumber" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fgiCaf" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BodyAttachment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="m1" ordered="false" lowerBound="1"
        eType="#//Mechanical" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="m2" ordered="false" lowerBound="1"
        eType="#//Mechanical" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialNumber" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fgiCaf" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DumperBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="m1" ordered="false" lowerBound="1"
        eType="#//Mechanical" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="m2" ordered="false" lowerBound="1"
        eType="#//Mechanical" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="m3" ordered="false" lowerBound="1"
        eType="#//Mechanical" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="m4" ordered="false" lowerBound="1"
        eType="#//Mechanical" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="m5" ordered="false" lowerBound="1"
        eType="#//Mechanical" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="m6" ordered="false" lowerBound="1"
        eType="#//Mechanical" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="m7" ordered="false" lowerBound="1"
        eType="#//Mechanical" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="m8" ordered="false" lowerBound="1"
        eType="#//Mechanical" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialNumber" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fgiCaf" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BodySideExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="m1" ordered="false" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialNumber" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fgiCaf" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TailLight">
    <eStructuralFeatures xsi:type="ecore:EReference" name="m1" ordered="false" lowerBound="1"
        eType="#//Mechanical" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialNumber" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fgiCaf" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimarySystem"/>
  <eClassifiers xsi:type="ecore:EClass" name="SecondarySystem"/>
  <eClassifiers xsi:type="ecore:EClass" name="DumperBobyUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wearplate" ordered="false"
        eType="#//Wearplate" containment="true">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="dumperbobyunit"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="spillguard" ordered="false"
        eType="#//Spillguard" containment="true">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="dumperbobyunit"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tailgate" ordered="false"
        eType="#//Tailgate" containment="true">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="dumperbobyunit"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bodyattachment" ordered="false"
        eType="#//BodyAttachment" containment="true">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="dumperbobyunit"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dumperbody" ordered="false"
        eType="#//DumperBody" containment="true">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="dumperbobyunit"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bodysideextension" ordered="false"
        eType="#//BodySideExtension" containment="true">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="dumperbobyunit"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taillight" ordered="false"
        eType="#//TailLight" containment="true">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="dumperbobyunit"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
